apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podnuker-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: podnuker-controller
    namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podnuker-controller

